# Generated by Django 3.2.9 on 2022-07-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surgery',
            options={'verbose_name': 'Операции'},
        ),
        migrations.AlterModelOptions(
            name='treatment',
            options={'verbose_name': 'Диагноз'},
        ),
        migrations.RemoveField(
            model_name='surgery',
            name='my_id',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='my_id',
        ),
    ]
