# Generated by Django 3.2.9 on 2022-07-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220712_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surgery',
            options={'ordering': ['article'], 'verbose_name': 'Операции'},
        ),
        migrations.AddField(
            model_name='surgery',
            name='article',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
