# Generated by Django 3.2.9 on 2022-06-29 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220628_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Диагноз')),
                ('image', models.ImageField(blank=True, null=True, upload_to='treatment')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentFullDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Описание')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_descriptions', to='home.treatment')),
            ],
        ),
    ]
