# Generated by Django 3.2.9 on 2022-06-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_treatment_treatmentfulldescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatmentfulldescription',
            old_name='news',
            new_name='treatment',
        ),
        migrations.AddField(
            model_name='treatment',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Диагноз'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Диагноз'),
        ),
        migrations.AddField(
            model_name='treatmentfulldescription',
            name='text_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='treatmentfulldescription',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
