# Generated by Django 3.2.9 on 2022-07-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_treatment_options_treatment_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Опыт'),
        ),
    ]
