# Generated by Django 3.2.9 on 2022-06-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220629_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentfulldescription',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заглавие'),
        ),
    ]
