# Generated by Django 3.2.9 on 2022-07-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_doctor_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['article'], 'verbose_name': 'Доктора'},
        ),
        migrations.AddField(
            model_name='doctor',
            name='article',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
