# Generated by Django 3.2.9 on 2022-06-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_treatmentfulldescription_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='вопросы')),
                ('answer', models.TextField(verbose_name='ответы')),
            ],
        ),
    ]
