# Generated by Django 3.2.9 on 2022-06-30 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_faq_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='description',
            options={'ordering': ['text'], 'verbose_name': 'Описание_врачей'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['full_name'], 'verbose_name': 'Доктора'},
        ),
        migrations.AlterModelOptions(
            name='fulldescription',
            options={'ordering': ['text'], 'verbose_name': 'Описание_новостей'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['title'], 'verbose_name': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='treatment',
            options={'ordering': ['title'], 'verbose_name': 'Диагноз'},
        ),
        migrations.AlterModelOptions(
            name='treatmentfulldescription',
            options={'ordering': ['text'], 'verbose_name': 'Описание_лечения'},
        ),
    ]
