# Generated by Django 3.2.9 on 2022-06-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220630_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews')),
                ('text', models.TextField(verbose_name='отзывы')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'ordering': ['name'],
            },
        ),
    ]
