# Generated by Django 3.2.9 on 2022-06-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='text_ky',
            field=models.TextField(null=True, verbose_name='отзывы'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='отзывы'),
        ),
    ]
