# Generated by Django 3.2.9 on 2022-07-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20220702_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_ky',
            field=models.TextField(null=True, verbose_name='ответы'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(null=True, verbose_name='ответы'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ky',
            field=models.CharField(max_length=300, null=True, verbose_name='вопросы'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='вопросы'),
        ),
    ]
