# Generated by Django 3.2.9 on 2022-07-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20220702_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='text_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='description',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
