# Generated by Django 3.2.9 on 2022-07-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_surgery_surgeryfulldescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Операции'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Операции'),
        ),
        migrations.AddField(
            model_name='surgeryfulldescription',
            name='text_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='surgeryfulldescription',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='surgeryfulldescription',
            name='title_ky',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заглавие'),
        ),
        migrations.AddField(
            model_name='surgeryfulldescription',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заглавие'),
        ),
    ]
