# Generated by Django 3.2.9 on 2022-07-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_surgery_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Картинка')),
                ('file', models.ImageField(blank=True, null=True, upload_to='work_images')),
            ],
            options={
                'verbose_name': 'Галерея_Контент',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название_видео')),
                ('file', models.FileField(upload_to='video', verbose_name='видео')),
            ],
            options={
                'verbose_name': 'Видео_Контент',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='surgery',
            options={'ordering': ['title'], 'verbose_name': 'Операции'},
        ),
    ]
