# Generated by Django 3.2.9 on 2022-07-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20220705_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagescontent',
            name='title_ky',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='imagescontent',
            name='title_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='title_ky',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название_видео'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='title_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название_видео'),
        ),
    ]
