# Generated by Django 3.2.9 on 2022-07-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20220705_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content'),
        ),
    ]
