# Generated by Django 3.2.9 on 2022-07-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_videocontent_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surgeryfulldescription',
            options={'ordering': ['my_id'], 'verbose_name': 'Описание_операция'},
        ),
        migrations.AddField(
            model_name='surgeryfulldescription',
            name='my_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='my_id'),
        ),
    ]
