# Generated by Django 3.2.9 on 2022-07-11 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20220711_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surgeryfulldescription',
            options={'ordering': ['id'], 'verbose_name': 'Описание_операция'},
        ),
        migrations.RemoveField(
            model_name='surgeryfulldescription',
            name='my_id',
        ),
    ]
