# Generated by Django 3.2.9 on 2022-07-11 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20220711_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatmentfulldescription',
            options={'ordering': ['id'], 'verbose_name': 'Описание_лечения'},
        ),
    ]
