# Generated by Django 4.0.5 on 2022-07-12 07:43

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_treatmentfulldescription_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surgery',
            options={'ordering': ['my_id'], 'verbose_name': 'Операции'},
        ),
        migrations.AddField(
            model_name='surgery',
            name='my_id',
            field=models.CharField(default=builtins.id, max_length=100, verbose_name='my_id'),
            preserve_default=False,
        ),
    ]
