# Generated by Django 4.0.5 on 2022-07-12 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_surgery_options_surgery_my_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surgery',
            options={'ordering': ['id'], 'verbose_name': 'Операции'},
        ),
    ]
