# Generated by Django 4.0.5 on 2022-07-12 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_surgery_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surgery',
            name='my_id',
        ),
    ]
