# Generated by Django 4.0.5 on 2022-07-12 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_remove_surgery_my_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surgery',
            options={'ordering': ['title'], 'verbose_name': 'Операции'},
        ),
    ]
